version = 0.1
[default.deploy.parameters]
stack_name = "acme-hello-world-ws-dev-infrastructure"
resolve_s3 = true
s3_prefix = "acme-hello-world-ws-dev-infrastructure"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "Prefix=\"acme\" ProjectId=\"hello-world-ws\" StageId=\"dev\" S3BucketNameOrgPrefix=\"\" RolePath=\"/\" DeployEnvironment=\"DEV\" FunctionGradualDeploymentType=\"AllAtOnce\" DeployRole=\"\" ParameterStoreHierarchy=\"/WebService/DEV/acme-hello-world-ws-dev/\" AlarmNotificationEmail=\"\" PermissionsBoundaryARN=\"\" FunctionTimeOutInSeconds=\"10\" FunctionMaxMemoryInMB=\"128\" ApiPathBase=\"hello-world-ws-dev\" UserAgent=\"Web Service\" LogRetentionInDaysForPROD=\"90\" LogRetentionInDaysForDEVTEST=\"7\" CacheDataDbMaxCacheSizeInKB=\"10\" CacheDataCryptIdHashAlgorithm=\"RSA-SHA256\" CacheDataCryptSecureDataAlg=\"aes-256-cbc\" CacheDataErrorExpirationInSeconds=\"300\" CacheDataPurgeExpiredCacheEntriesInHours=\"24\" CacheDataPurgeAgeOfCachedBucketObjInDays=\"15\" CacheDataTimeZoneForInterval=\"Etc/UTC\" CacheDataAWSXRayOn=\"false\""
image_repositories = []
